### ISSUE TITLE
blank nodes duplicated in bdr:P1583 after bdrc.owl update

### ISSUE THREAD

**Issue by xristy** [buda-base/git-to-dbs#10]
Nicolas noticed that the blank node elements of `bdr:P1583` were duplicated on buda1 after I rebuilt the triple store.

It seems to have happened during git-to-dbs. 

I checked `bdr:P314` and it seems fine. 

I checked the output from xmltoldmigration:

    ~/bdrc-gits/persons/fa/P1583.ttl

on buda1 and it looks normal. I've attached it here:

[P1583.ttl.txt](https://github.com/BuddhistDigitalResourceCenter/git-to-dbs/files/1653035/P1583.ttl.txt)

This occurred when I rebuilt the triple store after deleting the `inferSubtrees` from the bdrc.owl earlier for `:PersonName`, `:PersonEvent`, `:PlaceEvent`, and `:WorkTitle`.

I checked my local system which was built days ago before the ontology changes and it was fine.

So I started from scratch on my local system and reproduced the issue. I cd'd into git-to-dbs/ and did a `git pull` which said _up-to-date_ and then I did `git submodule update --init` which appeared to do nothing since the submodule was tied to a specific commit. I then cd'd into `./src/main/resources/owl-schema` and did `git checkout master ; git pull` and got the updated `bdrc.owl`, `context.json-ld`, and `lang-tags.md`. I did `mvn clean package` and ran the `git-to-dbs` as usual.

Sure enough `bdr:P1583` shows duplicated blank nodes and `bdr:P314` does not.

This is the same procedure I used on `buda1.bdrc.io` so apparently I somehow made a mistake in updating bdrc.owl, in general, or updating the bdrc.owl sub-module in git-to-dbs or perhaps there's some other problem.

**Comment by eroux** [comment]
I've been trying to reproduce this for a few hours, with no success, not sure what to do...

**Comment by eroux** [comment]
After a few attempts here's a (surprisingly fast) SPARQL query giving all the duplicates:

```sparql
PREFIX bdo: <http://purl.bdrc.io/ontology/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?r ?countDiff
WHERE {
  {
  ?r a bdo:Person .
  GRAPH ?r {
	  SELECT (count(?name) as ?count) (count(distinct ?name) as ?countDistinct)
		WHERE {
		  	?r bdo:personName/rdfs:label ?name
		}
    }
  } .
  FILTER (?count = 2 * ?countDistinct)
  BIND (?count - ?countDistinct as ?countDiff)
}
```

Strangely, if you remove the 

```
  ?r a bdo:Person .
```

the result becomes weird and I have no clue what's going on...

In the process, I noted that we have a lot of persons where the name is duplicate, for instance [P65](https://www.tbrc.org/xmldoc?rid=P65), [P863](https://www.tbrc.org/xmldoc?rid=P863), etc. I wonder if we should normalize that during the migration?

**Comment by eroux** [comment]
tried again but with the previous request I can say it for sure: I cannot reproduce this locally...

**Comment by eroux** [comment]
note that we have very interesting empty records like [P3JM47](https://www.tbrc.org/xmldoc?rid=P3JM47) (about a dozen)

**Comment by xristy** [comment]
I [added a test](https://github.com/BuddhistDigitalResourceCenter/git-to-dbs/blob/dbe889a01cbbb00d919e3d3ab150096351dca503/src/main/java/io/bdrc/gittodbs/TransferHelpers.java#L241) for whether a resource had already been processed and log the info. The test excludes Etexts since it appears that the RID appears twice to process the contents and the metadata.

I tested on a local machine and AWS and there were no reports of multiple occurrences of processing any resource; however, there are the usual P1583, P7497, and so on with double blank nodes.

It would appear that there is some other cause.

**Comment by xristy** [comment]
The doubling problem appears to be a problem in jena's RDFConnection and this will be reported in a jena issue. 

In the meantime there is a workaround via a new parameter, `-type`, for git-to-dbs that transfers a single type: Person, Work and so on, at a time. Running git-to-dbs for each type results in loading fuseki without doubling and the script, `migrate-all.sh` has been added to facilitate this.

There is also a file containing various SPARQL queries for testing for doubling of the various `:Entity`s, `FIND_DOUBLING_sparql.txt`.

**Comment by xristy** [comment]
I've removed all of the testing paths from git-to-dbs and retained the `-type` and `-bulkSz` options.

I thought I had an idea about the cause of the doubling but this morning when I spun up my local system I can not reproduce the problem at all!

Just to record what I thought might be causing the doubling: The usual _transfer all_ run of git-to-dbs starts off opening an `RDFConnectionFactory.connect` and a `DatasetAccessorFactory.createHTTP`. The transfers of individual resources via `TransferHelpers.syncType` occur over the RDFConnection and at the end of the transfers for the given type then the git revision is written over the `HTTP DataAccessor`.

All previous testing has shown that there is doubling of Persons (the first repo to be transferred) when the first bulk transfers of Items (the next repo to be transferred) occurs (-n 19053) and, I thought, the significance of this was that it was the first use of the `RDFConnection` after the use of the `DataAccessor` to transfer the git revision for Persons. But, since the problem is no longer happening in my test environment there's seemingly nothing more to do!

There is the `migrate-all.sh` script if the problem appears again.

**Comment by xristy** [comment]
Mea culpa! I was hitting the wrong test system. The behavior is still as it has always been.

I was able to disprove the conjecture about some sort of interference between `DataAccessor` and `RDFConnection` by running tests without the call to `FusekiHelpers.setLastRevision(gitRev, type);` at the end of transferring all the resources of a given type.

So, for now the bug is still there and the `migrate-all.sh` should be used to avoid the doubling.

**Comment by eroux** [comment]
Excellent, thanks a lot!
