### ISSUE TITLE
how to update owl-schema submodule

### ISSUE THREAD

**Issue by xristy** [buda-base/git-to-dbs#11]
I'd like to know how the owl-schema submodule is supposed to be updated since it gets pegged to a specific commit.

I've been cd'ing into `src/main/resources/owl-schema` and `git checkout master; git pull` and then pushing the git-to-dbs project.

Is this the appropriate method?

**Comment by eroux** [comment]
It is indeed

**Comment by xristy** [comment]
Thanks
