### ISSUE TITLE
chunks are in a different graph from the etext

### ISSUE THREAD

**Issue by eroux** [buda-base/git-to-dbs#17]
The current system uploads the chunks in a separate graph (probably the default one?) from the rest of the etext, see the difference between

```
construct {bdr:UT11577_004_0000 ?p ?o } where {
  bdr:UT11577_004_0000 ?p ?o
}
```

(which contains the chunks) and

```
construct {?s ?p ?o } where {
  graph bdg:UT11577_004_0000 {
     ?s ?p ?o
  }
}
```

(which doesn't).

**Comment by xristy** [comment]
I don't think we need to use two separate graphs: `bdg:UT11577_004_0000` and `bdg:UT11577_004_0000_STR` unless something in the retrieval and presentation of eTexts depends on two separate graphs.

I have merged, in [c0c0b03](https://github.com/buda-base/git-to-dbs/commit/c0c0b03915ba0f12a2a717a45596c4643ad8b595), the two which is what `EtextMergerTest.java` is doing.

**Comment by eroux** [comment]
ok for me

**Comment by xristy** [comment]
resolved by prior commits
