### ISSUE TITLE
chunks shouldn't be blank nodes

### ISSUE THREAD

**Issue by eroux** [buda-base/git-to-dbs#18]
Chunks are currently blank nodes, they should be named, see [this line](https://github.com/buda-base/git-to-dbs/blob/66fcc7f32dd1a22b8cd037ce6d0f31022e667dc9/src/main/java/io/bdrc/gittodbs/EtextContents.java#L67) and [this one](https://github.com/buda-base/git-to-dbs/blob/66fcc7f32dd1a22b8cd037ce6d0f31022e667dc9/src/main/java/io/bdrc/gittodbs/EtextContents.java#L78)

**Comment by xristy** [comment]
I noticed and am working on it as part of #16

**Comment by xristy** [comment]
resolved by prior commits
