### ISSUE TITLE
hang: updateFusekiLastSequence(lastSequence);

### ISSUE THREAD

**Issue by xristy** [buda-base/git-to-dbs#3]
line 168 TransferHelpers hangs:

    updateFusekiLastSequence(lastSequence);

log shows:

>[main] INFO fuseki-couchdb - Last doc transferred: wor:W8LS20695
[main] INFO fuseki-couchdb - Transferred 91123 docs to Fuseki
[main] INFO fuseki-couchdb - Updating sequence to 91123-g1AAAAGNeJzLYWBg4MhgTmEQTM4vTc5ISXLIyU9OzMnILy7JAUoxJTIkyf___z8rgzmJgUEnMRcoxp6cmpSSYmqCTQ8ek5IUgGSSPcgwkFGf8Cl1ACmNhyn1wqc0AaS0HqbUDI_SPBYgydAApICq54OVRxJUvgCifD9Y-QWCyg9AlN8HKddlJaj8AUQ52O3an7IAdUd_GQ

**Comment by eroux** [comment]
do you mean the timeout mechanism doesn't work? (it should use it)

**Comment by xristy** [comment]
Here's the command line:

    time java -jar target/fusekicouchdb-0.6.jar -transferAllDB -progress -doNotListen
