### ISSUE TITLE
searching in IDs and date fields

### ISSUE THREAD

**Issue by eroux** [buda-base/git-to-dbs#51]
An important aspect of the search on the current website is that identifiers like Derge number (ex: `D242`) and ISBNS (ex: `9789380359700`) can be found (if you select "search as identifier"), and dates can be found if you select "find as date". The new search should have that by (in the default search) adding a term match for the field `other_id`, and (if we can, I'm not sure how it works) a date match on `publication_date` (and then possibly other fields like `birth_date` that don't exist yet)

**Comment by eroux** [comment]
actually matching also on the `graphs` field would be good too

**Comment by roopeux** [comment]
Dates search has another ticket so I'll close this one.
