### ISSUE TITLE
Mappings fields for phonetics (from test)

### ISSUE THREAD

**Issue by roopeux** [buda-base/git-to-dbs#52]
Add two fields in mappings for the "pre-phonetics"
```
"prefLabel_prePhon": { "type": "text", "index_options": "offsets" },
"altLabel_prePhon": { "type": "text", "index_options": "offsets" },
```

**Comment by roopeux** [comment]
Lines added in https://github.com/buda-base/git-to-dbs/blob/elasticsearch/osmapping.json

**Comment by eroux** [comment]
I've put the new fields in the mappings of the live DB
