### ISSUE TITLE
using bdd: to describe the git revision of a graph

### ISSUE THREAD

**Issue by eroux** [buda-base/git-to-dbs#6]
I've opened a few small tasks on the [project](https://github.com/BuddhistDigitalResourceCenter/git-to-dbs/projects/1), i just use it as a todo list, but maybe it will prove more useful than that, we'll see... In the mean time, I think this issue will need some discussion:

We currently do not use the `bdd:` prefix at all, maybe we could start with the git revision of a graph transferred to fuseki. For instance if a file `W123.ttl` is at revision "abc" in git, maybe we could have

```ttl
bdd:W123 adm:hasGitRevision "abc"
```

? The other obvious case would be status, as it has to do with the metadata and not the data. But it's more tricky, as perhaps it would mean replacing (in git):

```ttl
bdr:W123 a :Work ;
    :status bdr:statusReleased ;
    ...
```

with

```ttl
bdd:W123 :status bdr:statusReleased .

bdr:W123 a :Work ;
    ...
```

?

**Comment by xristy** [comment]
this issue has been addressed via ```bda:``` and rfc011 reworking
