### ISSUE TITLE
JSONLDFormatter writes twice annotationProperty "note"

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/git-to-dbs#7]
It looks like the issue is coming from JsonLDWriter but the same problem arises when using jena model.write(os,lang) for any Jena format...using a model built from ttl file by RDFParserBuilder.parse(StreamRDFLib.graph(g)).

Tested within lds-rest API with resource C68 : TTL file is OK but direct query to fuseki for this resource  (DESCRIBE <http://purl.bdrc.io/resource/C68>) returns a "note "doubled" representation as well.

Obviously, something goes wrong in between ttl and fuseki.

**Comment by eroux** [comment]
diplicate of #10
